### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by elwis** [longnan/ksys-idempiere-docker-eclipse#1]
Great work. however I wasn't able to connect to anything at port 80.. 8080 worked a lot better for me ;)

> To access iDempiere-KSYS web-ui:
> http://docker-host-ip:80/webui
>

**Comment by longnan** [comment]
No problem for me.

Just reminder:
When you start docker container of ksys-idempiere-eclipse, you may add -p 80:8080 for port mapping from docker-host to docker-container.

**Comment by elwis** [comment]
You are right, I must have missed that of course. Thanks!
