### ISSUE TITLE
/tmp/ksys/jdk-8u102-linux-x64.tar.gz: Cannot open: No such file or directory when building container

### ISSUE THREAD

**Issue by richhl** [longnan/ksys-idempiere-docker-eclipse#2]
$>docker build --rm --force-rm -t longnan/ksys-idempiere-docker-eclipse:3.1.0.20160730 .

Sending build context to Docker daemon 325.1 kB
Sending build context to Docker daemon 
Step 0 : FROM phusion/baseimage:0.9.19
0.9.19: Pulling from phusion/baseimage
143997bb556a: Pull complete 
1ee92674a984: Pull complete 
0bb1d07e4d6b: Pull complete 
7bc86777be5f: Pull complete 
2fc17c1f5db4: Pull complete 
0d27f3fe5f78: Pull complete 
42cb44880ee1: Pull complete 
9d640c9f08d2: Pull complete 
4c5432f5da2b: Pull complete 
Digest: sha256:73cfb8db14843adf4797fda5b663650a1390466cdf94d39cfc178a42c0ef4767
Status: Downloaded newer image for phusion/baseimage:0.9.19
 ---> 4c5432f5da2b
Step 1 : MAINTAINER Ken Longnan ken.longnan@gmail.com
 ---> Running in d8225d063f8a
 ---> 370576bdaa55
Removing intermediate container d8225d063f8a
Step 2 : RUN locale-gen en_US.UTF-8 &&     echo 'LANG="en_US.UTF-8"' > /etc/default/locale
 ---> Running in 8471f00bb089
Generating locales (this might take a while)...
  en_US.UTF-8... done
Generation complete.
 ---> 6c0c2e8cb0f6
Removing intermediate container 8471f00bb089
Step 3 : RUN echo "deb http://mirrors.163.com/ubuntu/ trusty main restricted universe multiverse \n"         "deb http://mirrors.163.com/ubuntu/ trusty-security main restricted universe multiverse \n"         "deb http://mirrors.163.com/ubuntu/ trusty-updates main restricted universe multiverse \n"          "deb http://mirrors.163.com/ubuntu/ trusty-proposed main restricted universe multiverse \n"          "deb http://mirrors.163.com/ubuntu/ trusty-backports main restricted universe multiverse \n"       "deb-src http://mirrors.163.com/ubuntu/ trusty main restricted universe multiverse \n"          "deb-src http://mirrors.163.com/ubuntu/ trusty-security main restricted universe multiverse \n"         "deb-src http://mirrors.163.com/ubuntu/ trusty-updates main restricted universe multiverse \n"          "deb-src http://mirrors.163.com/ubuntu/ trusty-proposed main restricted universe multiverse \n"     "deb-src http://mirrors.163.com/ubuntu/ trusty-backports main restricted universe multiverse \n" > /etc/apt/sources.list
 ---> Running in c985b4318dea
 ---> a0b507ba7517
Removing intermediate container c985b4318dea
Step 4 : ADD ksys /tmp/ksys
 ---> 2a614e79431a
Removing intermediate container c8167b641ef3
Step 5 : ENV JDK8_FILE jdk-8u102-linux-x64.tar.gz
 ---> Running in 6b026330c3ae
 ---> c3ce02b5e142
Removing intermediate container 6b026330c3ae
Step 6 : RUN mkdir -p /usr/lib/jvm/jdk1.8.0/;
 ---> Running in 223047ed6023
 ---> 8b87fb4f1832
Removing intermediate container 223047ed6023
Step 7 : RUN tar --strip-components=1 -C /usr/lib/jvm/jdk1.8.0 -xzvf /tmp/ksys/$JDK8_FILE;
 ---> Running in 5963cfc7ae18
tar (child): /tmp/ksys/jdk-8u102-linux-x64.tar.gz: Cannot open: No such file or directory
tar (child): Error is not recoverable: exiting now
tar: Child returned status 2
tar: Error is not recoverable: exiting now
Removing intermediate container 5963cfc7ae18
INFO[0036] The command [/bin/sh -c tar --strip-components=1 -C /usr/lib/jvm/jdk1.8.0 -xzvf /tmp/ksys/$JDK8_FILE;] returned a non-zero code: 2

**Comment by longnan** [comment]
You have to download it by yourself manually from java.oracle.com, and put it in docker build folder.

**Comment by longnan** [comment]
You have to download it by yourself manually from java.oracle.com, and put it in docker build folder.
